# Décisions pour les signes NOUVEAU de arbitrage_micro_foeto.tsv (2026-09-28).
# Clé = index de la liste triée (organe, signe) produite par cree_signes_livres.py.
# "=FOETO:…" : terme tagué existant · ">N" : même signe que l'index N ·
# (organe_code, type, libellé fr) : terme à créer, tagué « verbatim » (verbatim de livre).
# Organe : code des ids v1 (PF.<ORG>) ou placenta PP.<ORG>.
D = {
0: ("END", "MET", "Cellules de la zone fasciculée claires, vacuolées, riches en lipides colorables"),
1: ("END", "MET", "Dépôts hyalins surrénaliens"),
2: ("PP.MEM", "MET", "Macrophages pigmentés dans le tissu conjonctif des membranes"),
3: ("PP.MEM", "MAL", "Excroissances polypoïdes du conjonctif à travers des défects épithéliaux amniotiques"),
4: ("ORL", "MAL", "Ligne de Schwalbe antéposée et élargie, avec crêtes de tissu mésodermique"),
5: ("COE", "MET", "Accumulation de matrice amorphe dans la média aortique"),
6: ("COE", "MAL", "Perte du contenu élastique de la paroi aortique"),
7: ("COE", "MAL", "Excès marqué de collagène dans la paroi aortique"),
8: ("COE", "MET", "Cellules valvulaires bleu alcian positives (valves aortique et mitrale)"),
9: ("COE", "VAS", "Lésions artérielles de type dysplasie fibromusculaire"),
10: ("CER", "MAL", "Désorganisation des noyaux gris centraux et du thalamus"),
11: ("SQU", "MAL", "Accumulation de spongieuse primaire et persistance de cartilage minéralisé métaphysaire"),
12: ("SQU", "MAL", "Travées osseuses hypercellulaires et minces"),
13: ("SQU", "MAL", "Os cortical hypercellulaire à grands ostéocytes"),
14: ("SQU", "MAL", "Structure lamellaire distordue en écailles de poisson"),
15: ("SQU", "MAL", "Désorganisation fibreuse avec travées osseuses trapues disposées au hasard"),
16: ("SQU", "MAL", "Moelle focalement fibreuse entre les travées osseuses"),
17: ">12", 18: ("SQU", "MET", "Signes histologiques d'ostéomalacie"), 19: ">12",
20: ("SQU", "MAL", "Réduction marquée du collagène des travées secondaires et de l'os cortical"),
21: ">16",
22: ("SQU", "MAL", "Remaniement non spécifique de la jonction chondro-osseuse"),
23: ("SQU", "MET", "Lésions péri-ostéocytaires non minéralisées"),
24: ("SQU", "MAL", "Maturation prématurée des chondrocytes"),
25: ("SQU", "MAL", "Îlots de cartilage métaplasique au centre de l'os"),
26: ("SQU", "MAL", "Îlots de cartilage métaplasique métaphysaires"),
27: ("SQU", "MAL", "Hypertrophie spongieuse à corticale mince"),
28: ("SQU", "INF", "Ostéomyélite stérile"),
29: ("SQU", "MAL", "Os primaire épais"),
30: ("HEM", "TUM", "Prolifération anormale de blastes myéloïdes, surtout mégacaryoblastes"),
31: ("HEM", "MAL", "Hypoplasie érythroïde médullaire"),
32: ">16", 33: ">16",
34: ("SQU", "MAL", "Ostéoclastes multinucléés incapables de résorber l'os"),
35: ">34",
36: ("CER", "MET", "Corps anormaux dans les axones et les dendrites"),
37: ("CER", "MAL", "Lobes temporaux anormalement développés"),
38: ("CER", "MAL", "Hypothalamus et neurohypophyse absents ou anormaux"),
39: ("CER", "VAS", "Cytoarchitecture cérébrale détruite par une perte neuronale étendue et une gliose"),
40: ("CER", "MET", "Dégénérescence des gaines de myéline de la substance blanche"),
41: ("CER", "MAL", "Amas de cellules dysmorphiques dans la substance blanche profonde"),
42: ("CER", "MAL", "Gliose fibrillaire en faisceaux dans la zone sous-piale"),
43: ("CER", "MAL", "Hétérotopie cérébrale"),
44: ("CER", "MET", "Inclusion d'aspect en rayon de miel ou en pavés"),
45: ("CER", "MET", "Inclusion à motif en arêtes de hareng (herringbone)"),
46: ("CER", "MAL", "Apoptose accrue"),
47: ("CER", "MET", "Pigment lipofuscinique accru (survie prolongée)"),
48: ("CER", "MAL", "Absence de corne d'Ammon"),
49: ("CER", "MET", "Surcharge neuronale prédominant sur la tête du noyau caudé et le putamen antérieur"),
50: ("CER", "MET", "Péricaryons fortement PAS positifs sur coupes congelées"),
51: ("CER", "MET", "Inclusions pléomorphes dans une cellule gliale"),
52: ("CER", "VAS", "Prolifération endothéliale"),
53: ("CER", "VAS", "Perte neuronale sévère et gliose du putamen postérieur"),
54: ("CER", "MET", "Matériel de surcharge en lamelles concentriques serrées"),
55: ("CER", "MET", "Matériel de surcharge dans les cellules gliales"),
56: ("CER", "VAS", "Destruction tissulaire dans le territoire des branches perforantes proximales de l'artère cérébrale moyenne"),
57: ("CER", "TUM", "Infiltrat mélanocytaire gagnant le parenchyme par les espaces de Virchow-Robin"),
58: ("CER", "MAL", "Absence de décussation des pyramides"),
59: ("CER", "MAL", "Tronc cérébral de petite taille"),
60: ("COE", "MAL", "Fibrose valvulaire mitrale sévère par accumulation de collagène"),
61: ("SQU", "MAL", "Matrice cartilagineuse anormale : fils fibrillaires entre zones kystiques acellulaires et zones de cellularité normale"),
62: ("SQU", "MAL", "Anomalies de la matrice cartilagineuse"),
63: ("SQU", "MET", "Chondrocytes entourés de matériel lamellaire en anneaux concentriques"),
64: ("SQU", "MAL", "Anneaux de collagène dense autour des chondrocytes"),
65: ("SQU", "MAL", "Chondrocytes hypertrophiques en disposition désordonnée"),
66: ">65",
67: ("SQU", "VAS", "Vaisseaux cartilagineux accrus avec fibrose périvasculaire"),
68: ">67",
69: ("SQU", "MAL", "Matrice cartilagineuse hétérogène à fibres de collagène grossières"),
70: ("SQU", "MET", "Pauvreté en protéoglycanes sulfatés de la matrice cartilagineuse"),
71: ("SQU", "MAL", "Matrice cartilagineuse raréfiée, remplacée en partie par des cellules plus nombreuses"),
72: ("SQU", "MET", "Cartilage ponctué"),
73: ("SQU", "MET", "Calcifications ponctuées des cartilages (larynx, sternum, rachis, épiphyses)"),
74: ("MUL", "MET", "Inclusions lamellées intracellulaires"),
75: ("CER", "MET", "Dendrites des cellules de Purkinje distendues par du matériel de surcharge"),
76: "=FOETO:PF.CER-MAL-158", 77: "=FOETO:PF.CER-MAL-158", 78: "=FOETO:PF.CER-MAL-291",
79: ("CER", "MAL", "Figures apoptotiques"),
80: ">79",
81: ("CER", "VAS", "Lésion cavitaire remplie de macrophages"),
82: "=FOETO:PF.CER-MAL-306",
83: ("CER", "MAL", "Neuroblastes à noyaux pycnotiques"),
84: ("CER", "MAL", "Substance grise épaisse en « double cortex »"),
85: ("CER", "MAL", "Dysplasie du cervelet"),
86: ("CER", "MAL", "Perte de la lamination cérébelleuse"),
87: ("ORL", "MAL", "Développement irrégulier de l'angle irido-cornéen"),
88: ("SQU", "MAL", "Chondrocytes dégénératifs à collagène péri-chondrocytaire (jonction chondro-osseuse)"),
89: ("ORL", "TUM", "Hémangiome choroïdien diffus"),
90: ">89",
91: ("CER", "MAL", "Nids massifs de cellules germinatives dans le noyau cochléaire"),
92: "=FOETO:PF.ORL-MAL-064",
93: ("ORL", "MET", "Vacuolisation marquée des cellules épithéliales cornéennes"),
94: ("COE", "MET", "Tissu fibreux coronaire à cellules vacuolées (mucopolysaccharidose)"),
95: ("COE", "MET", "Prolifération intimale coronaire riche en glycosaminoglycanes"),
96: ("CER", "MAL", "Quatrième couche corticale épaisse de neurones superficiels arrêtés dans leur migration"),
97: ("CER", "MAL", "Troisième couche corticale mince et paucicellulaire"),
98: ("CER", "MAL", "Ectopie neurogliale corticale"),
99: ">13",
100: ("ORL", "MAL", "Dégénérescence ballonnisante des fibres cristalliniennes postérieures"),
101: ("ORL", "MAL", "Désorganisation du cristallin"),
102: ("ORL", "MAL", "Liquéfaction des fibres cristalliniennes sous-jacentes"),
103: ("ORL", "MAL", "Prolifération fibroblastique sous la capsule antérieure du cristallin"),
104: ("PEA", "VAS", "Prolifération de capillaires bien différenciés, en nombre accru dans le derme"),
105: ("PEA", "VAS", "Vascularisation anormale du derme superficiel"),
106: ("PEA", "MAL", "Ossification membraneuse dermique (ostéome cutané)"),
107: ">106",
108: ("ORL", "TUM", "Dermolipome : épithélium conjonctival ou malpighien non kératinisé sur stroma surtout adipeux"),
109: ("PEA", "MAL", "Allongement des crêtes épidermiques"),
110: ("PEA", "MAL", "Grains de kératohyaline d'aspect spongiforme"),
111: ("PEA", "MAL", "Mélanocytes isolés en nombre accru le long de l'assise basale"),
112: ("ORL", "MAL", "Angle irido-cornéen anormalement développé"),
113: ("ORL", "MAL", "Absence de stroma cornéen"),
114: ("ORL", "MAL", "Absence de trabéculum"),
115: ("ORL", "MAL", "Aniridie avec absence des structures du segment antérieur"),
116: ("ORL", "MAL", "Choristome cartilagineux oculaire"),
117: ("ORL", "MAL", "Choristomes oculaires"),
118: ("ORL", "MAL", "Microcornée opaque"),
119: ("ORL", "MAL", "Nodule collagène à la jonction membrane de Descemet / trabéculum"),
120: ("ORL", "MAL", "Anomalies du développement de l'iris"),
121: ("ORL", "MAL", "Persistance de l'artère hyaloïde"),
122: ("ORL", "MAL", "Tissu glial prérétinien au contact de la tête du nerf optique"),
123: ">119",
124: ("ORL", "MAL", "Rétention de noyaux dans le cristallin"),
125: ("ORL", "MAL", "Membrane rétrocornéenne"),
126: ("ORL", "MAL", "Angle irido-cornéen rudimentaire"),
127: ("ORL", "VAS", "Vaisseaux dans le stroma cornéen"),
128: ("ORL", "MAL", "Cellules et globules de Wedl"),
129: ("MUL", "INF", "Inclusions intranucléaires éosinophiles pâles des normoblastes circulants et de leurs précurseurs"),
130: ("DIG", "MAL", "Faisceaux musculaires lisses arborescents entrecroisés dans le chorion"),
131: ("CER", "MAL", "Matrice germinale kystique"),
132: ("GEN", "MAL", "Cellules germinales immatures en excès (PLAP, POU5F1, KIT)"),
133: ("GEN", "MAL", "Perte rapide des cellules germinales après la mi-gestation"),
134: ("SQU", "MAL", "Prolifération et différenciation atypiques des chondrocytes"),
135: ">15",
136: ("SQU", "MAL", "Hypertrophie de la périphyse pénétrant la plaque de croissance"),
137: ("SQU", "MAL", "Zones hypocellulaires à cellules géantes multinucléées dans la plaque de croissance"),
138: ("DIG", "MAL", "Couche musculaire lisse surnuméraire sous-muqueuse"),
139: ("PEA", "MAL", "Cheveux aplatis et torsadés"),
140: ("COE", "MET", "Multiples fines gouttelettes lipidiques myocardiques"),
141: "=FOETO:PF.COE-INF-016", 142: "=FOETO:PF.COE-DYS-008", 143: "=FOETO:PF.COE-RET-022",
144: ("CER", "MAL", "Dysplasie hypothalamique"),
145: ("ORL", "MAL", "Hypoplasie du système vestibulaire périphérique"),
146: ("ORL", "MAL", "Densité très réduite des cellules ciliées vestibulaires"),
147: ("ORL", "MAL", "Nombre réduit de cellules du ganglion de Scarpa"),
148: ("DIG", "MET", "Dépôts hyalins de l'intestin grêle et du côlon"),
149: ">148",
150: ("DIG", "VAS", "Thrombi artériels intestinaux"),
151: ("ORL", "MAL", "Hyperplasie focale du stroma irien"),
152: ("REN", "NOR", "Blastème et 1 ou 2 générations de néphrons visibles"),
153: ("REN", "MAL", "Revêtement kystique de grandes cellules éosinophiles, parfois pluristratifié"),
154: ("REN", "MET", "Absence complète de marquage mégaline des tubules proximaux"),
155: ("REN", "MAL", "Tubes collecteurs kystiques cernés d'anneaux fibreux interstitiels"),
156: ("REN", "MAL", "Dilatations kystiques de tous les segments du néphron et des tubes collecteurs"),
157: ("REN", "MAL", "Épithélium kystique fréquemment dédifférencié"),
158: ("REN", "MET", "Épaississement hyalin diffus de la membrane basale glomérulaire, riche en fibrilles de collagène"),
159: "=FOETO:PF.REN-MAL-076",
160: ("REN", "VAS", "Hyalinose segmentaire et focale"),
161: "=FOETO:PF.REN-MAL-080",
162: ("REN", "MAL", "Fibrose interstitielle avec infiltrats inflammatoires, atrophie tubulaire, glomérulosclérose et kystes"),
163: ("REN", "MET", "Épaississement irrégulier de la membrane basale glomérulaire, aspect « mité »"),
164: ("REN", "MAL", "Néphronophtise : sclérose glomérulaire, fibrose interstitielle, dilatation tubulaire"),
165: ("REN", "MET", "Fibres collagènes dans la membrane basale et la matrice mésangiale"),
166: "=FOETO:PF.REN-MAL-076",
167: ("ORL", "MAL", "Luxation du cristallin"),
168: ("ORL", "MAL", "Rupture zonulaire"),
169: ("CER", "TUM", "Prolifération mélanocytaire atypique des leptoméninges"),
170: ("CER", "TUM", "Infiltrat mélanocytaire leptoméningé en nids, pigmentation mélanique éparse"),
171: ("CER", "TUM", "Infiltrat mélanocytaire leptoméningé en plaques ou diffus"),
172: ("FOI", "MAL", "Prolifération ductulaire biliaire"),
173: ("FOI", "MAL", "Transformation ductulaire marginale"),
174: "=FOETO:PF.FOI-MAL-062",
175: ("POU", "VAS", "Lésions artérielles pulmonaires de l'hypertension artérielle pulmonaire idiopathique"),
176: ("POU", "TUM", "Lymphangiomyomatose"),
177: ("HEM", "MET", "Dépôts hyalins ganglionnaires"),
178: ("CER", "MAL", "Hippocampes mal placés et grossièrement formés"),
179: ">26",
180: ("CER", "MAL", "Fusion des colliculi"),
181: ("CER", "MAL", "Fragmentation de la chromatine des motoneurones"),
182: ("CER", "MAL", "Pycnose des motoneurones"),
183: ("CER", "MAL", "Turgescence des motoneurones"),
184: ("MUS", "MAL", "Fibres de type 1 anormalement petites et fibres de type 2 anormalement grandes"),
185: ("MUS", "MAL", "Halo périphérique des fibres musculaires"),
186: ("MUS", "MAL", "Perte des fibres de type 1"),
187: ("MUS", "INF", "Infiltrats lymphocytaires musculaires marqués"),
188: ("MUS", "MAL", "Atrophie ou hypotrophie des muscles abdominaux"),
189: ("COE", "MET", "Dépôts hyalins myocardiques"),
190: ("COE", "MET", "Stéatose macrovésiculaire des cardiomyocytes"),
191: "=FOETO:PF.COE-DYS-008",
192: ("COE", "MET", "Myocarde vacuolé non nécrotique"),
193: ("MUL", "MAL", "Espaces irréguliers multiples dans un conjonctif abondant paucicellulaire (cou)"),
194: ("MUL", "MAL", "Espaces lymphatiques dilatés nombreux (cou)"),
195: ("CER", "MAL", "Dégénérescence cellulaire des noyaux des nerfs crâniens"),
196: ("PEA", "MAL", "Absence de cellules du périderme (épithélium buccal)"),
197: ("GEN", "MAL", "Stroma ovarien fusiforme indifférencié, follicules rares"),
198: ("PEA", "MAL", "Hyperkératose et acanthose palmo-plantaires"),
199: ("END", "MAL", "Conjonctif dense ou immature à canaux dilatés et distordus, acini et îlots rares ou absents"),
200: ("END", "MAL", "Canaux interlobulaires dilatés, remplis de mucus éosinophile, cernés de conjonctif abondant"),
201: ("END", "MAL", "Cellules caliciformes dans les canaux excréteurs intralobulaires"),
202: ("END", "MAL", "Fibrose interstitielle parenchymateuse du pancréas"),
203: ("END", "MAL", "Microkystes pancréatiques"),
204: ("END", "MAL", "Kystes pancréatiques"),
205: ("COE", "VAS", "Nécrose de coagulation du centre du pilier"),
206: ("PEA", "MAL", "Clarification cytoplasmique des kératinocytes"),
207: ("PEA", "MAL", "Clivage intrakératinocytaire à distance de la membrane cytoplasmique"),
208: ("PEA", "INF", "Inflammation du derme superficiel"),
209: ("PEA", "INF", "Inflammation du derme superficiel à éosinophiles"),
210: ("END", "MAL", "Cellules corticotropes hypophysaires raréfiées et dégénératives"),
211: ("PP.PLA", "MAL", "Villosités élargies, hypovasculaires, à éléments hématopoïétiques immatures"),
212: ("PP.PLA", "VAS", "Lésions prolifératives des capillaires fœtaux"),
213: ("PP.PLA", "TUM", "Hémangio-endothéliomes et chorangiomes multiples"),
214: ("PP.PLA", "MAL", "Placenta hydropique"),
215: ("PP.PLA", "TUM", "Cellules immatures mégacaryoblastiques, érythroblastiques ou primitives"),
216: ("PP.PLA", "INF", "Cellules à inclusions dans le syncytium et les cellules de Hofbauer"),
217: ("PP.PLA", "MET", "Infiltration par des macrophages augmentés de taille"),
218: ("PP.PLA", "VAS", "Thrombi intervilleux"),
219: ("PP.PLA", "MET", "Inclusions lysosomales placentaires"),
220: ("PP.PLA", "TUM", "Blastes circulants nombreux, mégacaryocytes immatures et précurseurs médullaires"),
221: ("PP.PLA", "INF", "Inclusions intranucléaires amphophiles des normoblastes"),
222: ("PP.PLA", "VAS", "Hématome sous-chorial tubéreux"),
223: ("DIG", "MAL", "Plexus myentérique ganglionnaire hypertrophié (rectum)"),
224: "=FOETO:PF.REN-MAL-008",
225: ("SQU", "MAL", "Cartilage de réserve hypercellulaire à grands chondrocytes à noyau central"),
226: ("SQU", "MAL", "Chondrocytes multinucléés dans le cartilage de réserve"),
227: ">226",
228: ("ORL", "MAL", "Hyperplasie de l'épithélium pigmentaire rétinien"),
229: "=FOETO:PF.ORL-MAL-052",
230: ("ORL", "MAL", "Dystrophie rétinienne"),
231: ("ORL", "MAL", "Plis rétiniens"),
232: ("ORL", "MET", "Cellules ganglionnaires rétiniennes à corps cytoplasmiques membraneux"),
233: ("ORL", "VAS", "Plis et excroissances rétiniens avec congestion des vaisseaux choroïdiens"),
234: ">228",
235: ("ORL", "MAL", "Choristome cartilagineux scléral"),
236: ("MUS", "MET", "Dépôts hyalins du muscle strié"),
237: ("MUS", "MAL", "Fibrose interstitielle du muscle strié"),
238: ("PEA", "MET", "Substance éosinophile amorphe PAS positive (derme)"),
239: ("PEA", "MAL", "Barre de cartilage mature dans l'hypoderme"),
240: ("PEA", "MAL", "Papillomatose « en boîte » avec hyperkératose et acanthose variable"),
241: ("PEA", "MAL", "Formation de bulles"),
242: ("PEA", "MET", "Métachromasie brune des cellules de Schwann"),
243: ("PEA", "MAL", "Fleurs de collagène"),
244: ("PEA", "MAL", "Tissu élastique réduit et annexes atrophiques"),
245: ("PEA", "MAL", "Fibrose dermique et dépôts d'hémosidérine"),
246: ("PEA", "MET", "Hyperkératose ostiale folliculaire dilatée avec dépôts de kératine calcifiée"),
247: ("PEA", "MAL", "Cellules dyskératosiques intra-épidermiques"),
248: ("PEA", "INF", "Infiltration à éosinophiles"),
249: ("PEA", "MAL", "Atrophie épidermique, incontinence pigmentaire, plexus périvasculaire superficiel saillant"),
250: ("PEA", "MET", "Granules de mélanine extracellulaires"),
251: ("PEA", "MAL", "Absence des fines fibres en candélabre du derme superficiel"),
252: ("PEA", "MET", "Dépôts hyalins dermiques"),
253: ">252", 254: ">252",
255: ("PEA", "MAL", "Hyperkératose, acanthose irrégulière et papillomatose"),
256: ("PEA", "MAL", "Mélanocytes en nombre accru à la jonction dermo-épidermique"),
257: ("PEA", "MET", "Gros dépôts globulaires d'élastine séparés des faisceaux microfibrillaires"),
258: ("PEA", "MET", "Mélanine dans des macrophages dermiques"),
259: ("PEA", "MAL", "Plans de clivage multiples"),
260: ("PEA", "MAL", "Porokératose"),
261: ("PEA", "MAL", "Réduction ou absence des petites fibres nerveuses cutanées"),
262: ("PEA", "MAL", "Annexes cutanées malformées et irrégulières"),
263: ("PEA", "MET", "Fibroblastes fusiformes dispersés dans un matériel hyalin abondant"),
264: ("PEA", "MAL", "Épiderme mince sans relief papillaire"),
265: ("PEA", "MET", "Inclusions de surcharge ultrastructurales des cellules de Schwann"),
266: ("MUL", "MET", "Vacuoles PAS positives d'aspect lysosomal (peau, foie, trachée, cœur)"),
267: ("CER", "MAL", "Cicatrice de la moelle épinière"),
268: ("CER", "MAL", "Moelle attachée, souvent avec lipome"),
269: ("CER", "MAL", "Épaississement du filum terminale"),
270: ("HEM", "MET", "Dépôts hyalins spléniques"),
271: ("GEN", "MET", "Calcifications intratubulaires testiculaires diffuses"),
272: ("HEM", "MET", "Dépôts hyalins thymiques"),
273: ("END", "MET", "Dépôts hyalins thyroïdiens"),
274: ("END", "MAL", "Cellules C thyroïdiennes en nombre accru, diffuses ou en amas"),
275: ("HEM", "TUM", "Excès de mégacaryoblastes avec fibrose locale"),
276: ("POU", "MAL", "Manchon cartilagineux trachéal continu"),
277: ("CER", "MAL", "Altération des noyaux du nerf hypoglosse (XII)"),
278: ("CER", "MAL", "Atrophie des faisceaux cortico-spinaux"),
279: ("PP.COR", "VAS", "Ulcération du cordon ombilical"),
280: ("COE", "MET", "Cellules claires nombreuses des feuillets valvulaires"),
281: ("CER", "MET", "Dégénérescence de la substance blanche"),
}
